### ISSUE TITLE
HTMLを綺麗なテスト画面にする

### ISSUE THREAD

**Issue by antitex** [antitex/antitex#16]
できるだけ簡潔に，サンプルコードと描画結果を書いていく
今の画面だとごちゃごちゃしすぎているので
```html
<div>
    <p>Matrix Test</p>
    <math class="antitex">
        mx([
            [1,null, O],
            [null, 1, null],
            [O, null, 1]
        ])
    </math>
</div>
```
みたいな感じで(上のはレイアウト例)統一する

**Comment by antitex** [comment]
https://github.com/antitex/antitex/issues/12
このやり方もついでに実装してもらえるとありがたいです〜

**Comment by 6br** [comment]
わかった。ただ実際の作業は明日になりそう
もしすぐ必要だったら先に進めててください。

**Comment by antitex** [comment]
もう少し綺麗にしたいので，closeはしないでおきます。

**Comment by 6br** [comment]
inputしたらそれをmathML形式にして表示してくれるようなものがほしい
