### ISSUE TITLE
外部ライブラリの作成

### ISSUE THREAD

**Issue by 6br** [antitex/antitex#23]
AntiTeXの内部で実装するほどprimitiveではないけれど、実際に数式や図を書く上で便利な記法やメソッドをライブラリのような形で提供するのはどうだろうか。
入れるとしたら、どのようなものがありうるだろうか。

**Comment by antitex** [comment]
それは，antitexではなく，例えば[mathdraw.js]みたいな名前をつけて独立のプロジェクトにすべきだと思う。
いろいろ入れると複雑になるし。
6brで新しくリポジトリを作ってくれたらそっちも[余裕があれば]コミットするので，ぜひ作ってください

**Comment by 6br** [comment]
グラフについては出力するjsのライブラリは既に色々あるので、それを適宜使えば十分ですかね。
http://www.fwoabw.info/entry/2013/09/24/008062
