### ISSUE TITLE
多項関数まとめ

### ISSUE THREAD

**Issue by antitex** [antitex/antitex#6]
多項関数(+,-,*,%)をまとめてprototypeに追加する。

ラテン・ギリシャ文字のまとめて追加を参考とせよ。

**Comment by antitex** [comment]
例えば`+`は`ad(a,b,c,...)`と与えられた時`a+b+c+...`でいいと思うけど
`difbyx`は`difbyx(x,y,z,...)`と与えられた時`df(x,y,z,...)/dx`と表記しなくちゃいけないから、ここで扱うのは間を記号で区切るものだけということにしたほうが良いかも知れない

**Comment by 6br** [comment]
I agree.

**Comment by antitex** [comment]
対応しました。
