### ISSUE TITLE
ベクトル

### ISSUE THREAD

**Issue by 6br** [antitex/antitex#9]
縦ベクトルと横ベクトルの相互変換
（縦ベクトル記法で書いたものを横ベクトルで表示）

**Comment by antitex** [comment]
```JavaScript
vt(mx([0,1,2,x])) // 縦に表示される
```
みたいな感じ?

**Comment by 6br** [comment]
そうです。

**Comment by antitex** [comment]
`vmx([0,1,2,x])`だけで縦に表示できたほうがいいのでは?
`vt(mx([0,1,2,x]))`だと一度XMLをパースしないといけないみたい

**Comment by antitex** [comment]
実装を
よろしく～ねっ！

**Comment by 6br** [comment]
りょーかいです
vt(mx([0,1,2,x]))となる必要性はあまりないかも

**Comment by 6br** [comment]
var _mx = mx([0,1,2,x])としているときのように明示的に定義された行列を逆行列にしたい場合は
vt(_mx)とできるとうれしいかもしれない

**Comment by antitex** [comment]
https://developer.mozilla.org/ja/docs/Parsing_and_serializing_XML
に文字列をXMLにパースするやり方があるから，コードを簡潔に保てるのであればXMLを作りなおしてもいいかも。
でも，普通Aの転置行列はA^Tで済ませちゃうと思うので，できればXMLパースの方の実装は後回しにしてください。

**Comment by antitex** [comment]
`vmx`は，mtxのシンタックスシュガーで実現できるからそんなに難しくないはず
```
// これを
mx([
  [0],
  [1],
  [x],
],open,close)
// こう書きたい
vmx([0,1,2], open, close)
```

**Comment by 6br** [comment]
XMLパースの実装は当面パスでいいですか

**Comment by antitex** [comment]
いいと思います
